### ISSUE TITLE
Request support for Redmi 9A 64-bit in Lineage 18.1

### ISSUE THREAD

**Issue by openwrt2223** [dandelion64-Archives/android_device_xiaomi_blossom#3]
Request support for Redmi 9A 64 bit in LineageOS 18.1

**Comment by ookiineko** [comment]
need backport tree to a11

**Comment by openwrt2223** [comment]
> need backport tree to a11

When to do it?

**Comment by ookiineko** [comment]
> When to do it?

idk, but you can try it in your fork. also this is not an issue with this A13 device tree.

**Comment by openwrt2223** [comment]
> > When to do it?
> 
> idk, but you can try it in your fork. also this is not an issue with this A13 device tree.

The lineage 20 device tree doesn't work directly on lineage 18.1, I modified it, but it went straight to fastboot BL.

**Comment by ookiineko** [comment]
> The lineage 20 device tree doesn't work directly on lineage 18.1, I modified it, but it went straight to fastboot BL.

what does the log say?

**Comment by openwrt2223** [comment]
> > The lineage 20 device tree doesn't work directly on lineage 18.1, I modified it, but it went straight to fastboot BL.
> 
> what does the log say?

I don't know how to get the logs

**Comment by ookiineko** [comment]
> I don't know how to get the logs

add a kernel command-line to boot image: `androidboot.init_fatal_reboot_target=recovery`, and it may reboot to recovery instead. then extract `/sys/fs/pstore` from the device.
